### ISSUE TITLE
Test out a new contribution event!

### ISSUE THREAD

**Issue by isabela-pf** [Quansight-Labs/jupyter-a11y-mgmt#132]
## Summary

Based on sprint planning discussions in #114. Related to one element of #3. 

After the work to brainstorm event ideas and loose agendas, I want to choose one of the proposed events and test it out for further development.

## Acceptance Criteria

This issue can be closed when a prototype event has been run, agenda linked, and feedback from the event noted (all linked on this issue).

## Tasks to complete

- [x] Select a proposed event to clean up
- [x] Choose project/area to design the event around
- [x] Develop agenda, event resources, all logistics needed to prepare
- [x] Schedule event
- [x] Run event
- [x] Get event feedback
- [x] Record changes wanted for the future
- [x] Open next steps

**Comment by isabela-pf** [comment]
The [keyboard navigation event](https://github.com/isabela-pf/a11y-events/tree/main/workshop-resources/keyboard-navigation) had its first rough trial run on October 12. Full info on the [event agenda](https://hackmd.io/cBWlnRcGQ6OBmQ4wCOjBWw?view).

**Comment by isabela-pf** [comment]
The keyboard navigation event had it's [second rough trial on November 21](https://github.com/isabela-pf/a11y-events/pull/11). With some notes and documentation, I think this issue can be closed.

**Comment by isabela-pf** [comment]
Feedback is posted [on comments on one of the working PRs](https://github.com/isabela-pf/a11y-events/pull/10#discussion_r993809574). With this I'll close the issue since no immediate next steps will be happening in the near future. Thank you!
