### ISSUE TITLE
Fix tab traps in JupyterLab

### ISSUE THREAD

**Issue by isabela-pf** [Quansight-Labs/jupyter-a11y-mgmt#134]
## Summary

Based on sprint planning discussions in #114.

Quoting from #114:
> Fix tab traps in the Lumino menu bar and then in JupyterLab if more adjustments are needed (@gabalafou)

## Acceptance Criteria

Tab trap-focused PRs are merged in relevant projects that build JupyterLab and we've tested to confirm the changes.

## Tasks to complete

This would need to be ironed out if we choose to pursue this is a sprint.

**Comment by gabalafou** [comment]
Here are some sub-tasks that would need to be completed before I would consider this done done:

- [ ] Fix keyboard trap in open notebook (there needs to be a simple way to get out of the notebook and to other parts of the UI using only the tab, arrow, or esc keys. See [WCAG 2.1.2 No Keyboard Trap](https://www.w3.org/TR/WCAG22/#no-keyboard-trap)
- [ ] Fix keyboard trap in terminal. It's possible to close the terminal by typing `CTRL`+`D` but this probably either needs to be communicated, or we need to provide a more standard keyboard shortcut.
- [ ] More extensively audit the UI for other keyboard traps.
- [ ] Provide visual indicator of moving tab focus. Right now it's difficult to know where you are in the UI as you tab through it.
