### ISSUE TITLE
Rendered notebook user testing - Round 1

### ISSUE THREAD

**Issue by isabela-pf** [Quansight-Labs/jupyter-a11y-mgmt#146]
## Summary

This is a part of the [STScI collaborative rendered notebook research](https://github.com/Iota-School/notebooks-for-all). We're working together to run accessibility-focused user testing on static forms of notebooks. The aim is to provide open research for the betterment of the community and to learn more about accessibility needs in all notebooks by starting with their static versions. I've been asked to open issues for these tasks in this repo for easier tracking.

The first user test will feature navigation and structure-focused tasks. Goals for this set of tests include
- To better understand patterns in high-level organization and navigation of the notebook
- To better understand what information users have access to and search for (as well as what might be missing)
- To identify user pain points and asks for future improvement.

## Acceptance Criteria

This issue may be closed when all user testing information for this round is stored in the [project repo](https://github.com/Iota-School/notebooks-for-all) and recorded/linked in this isssue.

(If you can think of something else, let me know!)

## Tasks to complete

- [ ] Consolidate and template what we can for future testing rounds 
- [ ] User testing script is completed
- [ ] Test logistics finalized
- [ ] All round 1 tests have been run
- [ ] Process all round 1 test data (and store!)
- [ ] All public (and non-identifiable info) is stored in the [project repo](https://github.com/Iota-School/notebooks-for-all) and linked as resources from jupyter/accessibility

**Comment by isabela-pf** [comment]
The first test's [work in progress resources are in PR form](https://github.com/Iota-School/notebooks-for-all/pull/26). I won't check the to do point off until it is complete, but this is an update.

**Comment by isabela-pf** [comment]
Update: The first test's results and resources are in ready-to-merge form. I'm looking for review and then it's good to go.
