### ISSUE TITLE
Rendered notebook user testing - Round 2

### ISSUE THREAD

**Issue by isabela-pf** [Quansight-Labs/jupyter-a11y-mgmt#147]
## Summary

This is a part of the [STScI collaborative rendered notebook research](https://github.com/Iota-School/notebooks-for-all). We're working together to run accessibility-focused user testing on static forms of notebooks. The aim is to provide open research for the betterment of the community and to learn more about accessibility needs in all notebooks by starting with their static versions. I've been asked to open issues for these tasks in this repo for easier tracking.

The second user test will explore notebook content types. Goals for this set of tests include
- To explore a how wide range of notebook content types are rendered, especially cell outputs
- To better understand the rendered status of all supported notebook content types
- To better understand what content have access to and what might be missing
- To identify user pain points and needs for interacting with a range of content types

## Acceptance Criteria

This issue may be closed when all user testing information for this round is stored in the [project repo](https://github.com/Iota-School/notebooks-for-all) and recorded/linked in this issue.

(If you can think of something else, let me know!)

## Tasks to complete

- [ ] User testing script is completed
- [ ] Test logistics finalized
- [ ] All round 2 tests have been run
- [ ] Process all round 2 test data (and store!)
- [ ] All public (and non-identifiable info) is stored in the [project repo](https://github.com/Iota-School/notebooks-for-all) and linked as resources from jupyter/accessibility

**Comment by isabela-pf** [comment]
This is in progress! The test script is in progress, but I will keep this updated as we work.

**Comment by isabela-pf** [comment]
[Test 2 results](https://github.com/Iota-School/notebooks-for-all/blob/main/user-tests/2-content/results.md) have been merged! 

I won't close this because of the above comment that they need to be linked in jupyter/accessibility. But I will return to close it then.
