### ISSUE TITLE
[DOC]-  Add accessibility documentation to JupyterLab docs (user)

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#173]
Need to open a PR to add a documentation section on accessibility - with inspiration from https://code.visualstudio.com/docs/editor/accessibility 

```[tasklist]
### TODO
- [x] Scope content - will be done collaboratively @steff456  will start a Google Doc
- [x] Review references in https://github.com/jupyter/accessibility/issues/15
- [ ] Create an accessibility-focused documentation page in JupyterLab docs https://github.com/jupyterlab/jupyterlab/issues/14396
- [x] Notebook authoring guide (Based on [Notebooks For All findings](https://github.com/Iota-School/notebooks-for-all/blob/main/resources/event-hackathon/notebook-authoring-checklist.md) and mentioned in [jupyter/accessibility #125](https://github.com/jupyter/accessibility/issues/125))
```

**Comment by trallard** [comment]
@isabela-pf discussed the Accessibility statement at the global council meeting

Next: recorded stuff -> contribute to JupyterLab (from https://jupyter-accessibility.readthedocs.io/en/latest/resources/JupyterLab-a11y-statement.html)

**Comment by steff456** [comment]
Brainstorm of ideas -> https://docs.google.com/document/d/1b-MvWfNhsJGWZ-YfU86YosMFTkhTICvjUUtDOi8d6AM/edit?usp=sharing

**Comment by trallard** [comment]
By the end of the sprint? January 5th 

I will take on finding themes in the wild and identifying if any accessibility affordances built it.
Also can dig into what is possible with customisation right now (with the settings)

**Comment by trallard** [comment]
On this same effort - we are submitting a Google Season of Docs proposal see https://docs.google.com/document/d/1gbPzQuVGa2eIeK6T4eNaxoW4qK9XXg9MSOVoHh_AGlo/edit

**Comment by isabela-pf** [comment]
Unexpectedly, the [JupyterLab user testing](https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/184) efforts gave us some insight to details that might be helpful to include around user-facing accessibility documentation in JupyterLab. I'll summarize the points here for safe keeping.

- Make keyboard shortcuts more easily available in JupyterLab docs.
- Mention the command palette in the JupyterLab accessibility docs. This seems like it has the potential to be helpful, but was not well known by several participants.
- Call out how to make cell execution chime (or other notification) when complete. Some participants said they’d heard of it, but have no idea how to do it. (Note: I'm not sure this is possible in default JupyterLab, but it is worth checking.)
- Mention font size, theme, and other UI modifications in JupyterLab accessibility docs, even if it is only to link to further documentation on it.

**Comment by trallard** [comment]
Closing this meta issue - the user docs issue will remain open as Stephannie is working on this with Johnson
