### ISSUE TITLE
Setup JLab user testing environment

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#192]
We must ensure we have a reproducible and easy-to-access environment for user testing.

```[tasklist]
### TODO
- [x] Setup repo `Quansight-Labs/JLab-user-testing-setup`
- [x] Define a list of requirements
- [x] Spin-up environment
- [x] Add contents with [nbgitpuller](https://tljh.jupyter.org/en/latest/howto/content/nbgitpuller.html) - the content is in the repo
- [x] Document how to deploy the infrastructure
- [x] Internal team testing (pre-user testing) - CZI-a11y team
- [x] Tear down and send costs for billing
```

```[tasklist]
### Requirements
- [x] [TLJH deployment](https://tljh.jupyter.org/en/latest/index.html)
- [x] [Latest JupyterLab stable release](https://github.com/jupyterlab/jupyterlab/releases)
- [x] Ensure that the default [user interface is set to JupyterLab](https://tljh.jupyter.org/en/latest/howto/env/notebook-interfaces.html#trying-an-alternate-interface-temporarily)
- [x] Low friction authentication mechanism
- [x] Should have write access to the working directory
```

Infra issue https://github.com/Quansight/quansight-cloud-infrastructure/issues/6

```[tasklist]
### Identified content needed
- [x] Source for [numpy/numpy-tutorials Saving and Sharing your NumPy Arrays](https://github.com/numpy/numpy-tutorials/blob/main/content/save-load-arrays.md)
```

Assigning @costrouc as he is our POC

**Comment by trallard** [comment]
FYI @costrouc  and @isabela-pf  the repository for the User testing infra and scripts is at https://github.com/Quansight-Labs/JupyterLab-user-testing
