### ISSUE TITLE
[GOAL] - Document accessibility journey

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#196]
We will ensure that our work is recorded and can be used to support future accessibility efforts in the PyData ecosystem.

```[tasklist]
### TODO
- [ ] https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/18
- [ ] https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/173
- [ ] https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/178
- [ ] https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/208
- [ ] https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/220
- [ ] https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/30
```

```[tasklist]
### Stretch / deferred
- [ ] https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/31
```

**Comment by trallard** [comment]
💡  Write a GSDocs proposal for a11y focused docs https://developers.google.com/season-of-docs/docs/timeline

24th March
