### ISSUE TITLE
Fix focus issues in Lumino menu bar

### ISSUE THREAD

**Issue by gabalafou** [Quansight-Labs/jupyter-a11y-mgmt#225]
## Summary

A cursor is to a mouse what focus (and focus indicator) are to the keyboard. 

The Lumino menu bar has a number of focus anti-patterns, such as: moving focus on mouse over (it generally shouldn't move unless a key has been pressed or the mouse has been clicked), not moving browser focus as the user navigates the menu with a keyboard, and others.

## Acceptance Criteria

- [ ] The JupyterLab [focus visible test](https://github.com/Quansight-Labs/jupyter-a11y-testing/pull/33) passes 
- [ ] Focus does not move when user moves mouse over menu bar item
- [ ] Focus does move when user uses keyboard to select item in menu bar
- [ ] Pressing escape does not lose focus to the document body

## Tasks to complete

- [ ] Watch PhosphorJS mentor sessions to better understand the code architecture and philosophy of Lumino
- [ ] Submit PR that resolves active state versus focus state
- [ ] Maybe: try to get Phosphor author to look at PR 
- [ ] Merge PR

**Comment by gabalafou** [comment]
Note, the one part of the acceptance criteria that https://github.com/jupyterlab/lumino/pull/607 does not meet is:

 Pressing escape does not lose focus to the document body
