### ISSUE TITLE
[DEL]- Contribute automated tests to PyData Sphinx theme

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#26]
## Background

Automated tests contributed to at least one other project in the Jupyter ecosystem.
Depends on #25 

This should help us create a framework for a11y related work for the broader ecosystem

```[tasklist]
### TODO
- [x] Review what is already in https://github.com/pydata/pydata-sphinx-theme/pull/294
- [x] Since we are using playwright elsewhere, it might be worth using across the projects to have consistent tooling and recommendations
- [x] Add tests + documentation
```

**Comment by scmmmh** [comment]
@trallard Excellent! Anything you could come up with to simulate keyboard navigation would be of massive interest to any project wanting to do automated a11y testing.

**Comment by trallard** [comment]
@gabalafou has been looking into keyboard navigation and tests for a bit now. 
We will make sure to share our findings.

**Comment by trallard** [comment]
Deliverable for Sci Python grant

**Comment by trallard** [comment]
Marking as complete as these are now merged and working. Next iterations should fall under the other grant
