### ISSUE TITLE
[DEL] - Adequate colour contrast for interactive regions.

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#8]
```[tasklist]
### Tasks
- [ ] https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/40
- [x] Items needing extra attention: input boxes, cell collapser, cell borders (multiple states)
- [x] Check: interactive elements (hover, active....
```

We might assess later and decide *if* and *which* changes would need to go into core
