### ISSUE TITLE
Look into adding "last updated" to JupyterLab docs

### ISSUE THREAD

**Issue by gabalafou** [Quansight-Labs/jupyter-a11y-mgmt#81]
## Summary
When looking at docs, I think it's important to know if they've been updated recently or not. It might be as simple as adding a single line or it might require a change to the ReadTheDocs software. Investigate.

## Acceptance Criteria
Either of:
- A new PR which adds this string to each page in the JupyterLab docs OR
- A new GitHub issue requesting to add this functionality to ReadTheDocs

## Tasks to complete
- [ ] Search through the documentation for ReadTheDocs
- [ ] Search through the GitHub issues on ReadTheDocs and JupyterLab
- [ ] Learn more about ReadTheDocs
- [ ] If not supported by ReadTheDocs, try to see if there is nonetheless an existing, low-effort pathway 
- [ ] If not, open issue wherever is most appropriate
